version: "3.8"
services:
  project-lottery-redis:
    container_name: project-lottery-redis
    build:
      dockerfile: Dockerfile
      context: ./redis
    image: pyo92/project-lottery-redis
    ports:
      - "6379:6379"
  project-lottery-database:
    container_name: project-lottery-database
    build:
      dockerfile: Dockerfile
      context: ./database
    image: pyo92/project-lottery-database
    environment:
      - MARIADB_DATABASE=lottery
      - MARIADB_ROOT_PASSWORD=${LOCAL_DATASOURCE_PASSWORD}
    volumes:
      - ./database/config:/etc/mysql/conf.d
      - ./database/init:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
  project-lottery-selenium:
    container_name: project-lottery-selenium
    build:
      dockerfile: Dockerfile
      context: ./selenium
    volumes:
      - /dev/shm:/dev/shm
    shm_size: 2g
    environment:
      - SE_SCREEN_WIDTH=1920
      - SE_SCREEN_HEIGHT=768
    ports:
      - "4444:4444"
      - "5900:5900"
      - "7900:7900"
