version: "3.8"
services:
  project-lottery-redis:
    container_name: project-lottery-redis
    build:
      dockerfile: Dockerfile
      context: ./redis
    image: pyo92/project-lottery-redis
    ports:
      - "6379:6379"
  project-lottery-selenium-for-scrap:
    container_name: project-lottery-selenium-for-scrap
    build:
      dockerfile: Dockerfile
      context: ./selenium
    image: pyo92/project-lottery-selenium-for-scrap
    volumes:
      - /dev/shm:/dev/shm
    shm_size: 256mb
    environment:
      - SE_SCREEN_WIDTH=1024
      - SE_SCREEN_HEIGHT=768
      - SE_NODE_MAX_SESSIONS=1
    ports:
      - "4444:4444"
      - "5900:5900"
      - "7900:7900"
  project-lottery-selenium-for-purchase:
    container_name: project-lottery-selenium-for-purchase
    build:
      dockerfile: Dockerfile
      context: ./selenium
    image: pyo92/project-lottery-selenium-for-purchase
    volumes:
      - /dev/shm:/dev/shm
    shm_size: 256mb
    environment:
      - SE_SCREEN_WIDTH=1024
      - SE_SCREEN_HEIGHT=768
      - SE_NODE_MAX_SESSIONS=1
      - SE_NODE_SESSION_TIMEOUT=60
    ports:
      - "4445:4444"
      - "5901:5900"
      - "7901:7900"
