spring:
  profiles:
    active: local #default
    group:
      local:
        - common
      prod:
        - common

---

spring:
  config:
    activate:
      on-profile: common
  jpa:
    properties:
      hibernate:
        default_batch_fetch_size: 100

kakao:
  js:
    key: ${KAKAO_JAVA_SCRIPT_KEY}
  rest:
    api:
      key: ${KAKAO_REST_API_KEY}

---

spring:
  config:
    activate:
      on-profile: local
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/lottery
    username: ${LOCAL_DATASOURCE_USERNAME}
    password: ${LOCAL_DATASOURCE_PASSWORD}
  data:
    redis:
      host: localhost
      port: 6379
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true
  sql:
    init:
      mode: never

---

spring:
  config:
    activate:
      on-profile: prod
