spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE}
    group:
      dev:
        - common
      prod:
        - common

---

spring:
  config:
    activate:
      on-profile: common
  jpa:
    properties:
      hibernate:
        default_batch_fetch_size: 100
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://${DATASOURCE_URL}:${DATASOURCE_PORT}/${DATASOURCE_SCHEMA}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: ${KAKAO_REST_API_KEY}
            client-secret: ${KAKAO_OAUTH_CLIENT_SECRET}
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/kakao"
            client-authentication-method: POST
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

dhlottery:
  encryption:
      key: ${DH_LOTTERY_ENCRYPTION_KEY}

kakao:
  js:
    key: ${KAKAO_JAVA_SCRIPT_KEY}
  rest:
    api:
      key: ${KAKAO_REST_API_KEY}
  oauth:
    logout:
      redirection:
        url: ${KAKAO_OAUTH_LOGOUT_REDIRECTION_URL}

selenium:
  hub:
    scrap:
      url: ${SELENIUM_HUB_FOR_SCRAP_URL}
    purchase:
      url: ${SELENIUM_HUB_FOR_PURCHASE_URL}

---

spring:
  config:
    activate:
      on-profile: dev
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: never

---

spring:
  config:
    activate:
      on-profile: prod
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: never

server:
  port: 443
  ssl:
    enabled: true
    key-store-type: PKCS12
    key-store: /etc/letsencrypt/live/gp-lottery.shop/keystore.p12
    key-store-password: dlfekd!100